-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Dashboard exposing (..)

import I18Next exposing (Delims(..), Translations, tf, trf)


greeting : List Translations -> String -> String
greeting translations name =
    trf translations Curly "dashboard.greeting" [ ( "name", name ) ]
