-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Login exposing (..)

import I18Next exposing (Delims(..), Translations, tf, trf)


buttonPrompt : List Translations -> String
buttonPrompt translations =
    tf translations "login.buttonPrompt"
