name:                server
version:             0.1.0.0
license:             BSD3
author:              "Tony Bradley"
maintainer:          "antbradley91@gmail.com"
copyright:           "2022 Tony Bradley"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:        See README.md

dependencies:
- base >= 4.7 && < 5
- relude
- scotty
- wai-middleware-static
- monad-logger
- wai
- http-types
- envy
- warp
- dotenv
- mongoDB
- hedis
- transformers
- aeson
- network
- uuid
- cookie
- text
- bson
- exceptions
- async
- binary

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
    - LambdaCase
    - NoImplicitPrelude
    - TupleSections
    - OverloadedStrings
    - OverloadedRecordDot
    - ImportQualifiedPost

executables:
  server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - server

tests:
  teo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - teo
