-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations exposing (..)

import I18Next exposing (Delims(..), Translations, tf, trf)


hello : List Translations -> String -> String
hello translations world =
    trf translations Curly "hello" [ ( "world", world ) ]
